name: Build Userscript

on:
  push:
    branches:
      - main

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.9.0
          run_install: true
      - run: |
          pnpm build
          # backward compatibility
          cp dist/bdwm-helper.user.js dist/bdwm-helper.iife.user.js
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    name: Deploy the Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
